@GameScoreTrackerRestApi_HostAddress = http://localhost:5098

GET {{GameScoreTrackerRestApi_HostAddress}}/GameScoreTracker/gamescores/alma

###


GET {{GameScoreTrackerRestApi_HostAddress}}/GameScoreTracker/games

###

GET {{GameScoreTrackerRestApi_HostAddress}}/GameScoreTracker/players

###

GET {{GameScoreTrackerRestApi_HostAddress}}/GameScoreTracker/gamescores?title=doom

###

GET {{GameScoreTrackerRestApi_HostAddress}}/GameScoreTracker/gamescores/doom

###


GET {{GameScoreTrackerRestApi_HostAddress}}/GameScoreTracker/playergamescores?player=Alice&title=doom

###







GET {{GameScoreTrackerRestApi_HostAddress}}/GameScoreTracker/rank/doom/5

###


GET {{GameScoreTrackerRestApi_HostAddress}}/GameScoreTracker/playerscores?player=balint

###

GET {{GameScoreTrackerRestApi_HostAddress}}/GameScoreTracker/playergamescores?title=doom&player=balint
###

GET {{GameScoreTrackerRestApi_HostAddress}}/GameScoreTracker/players
###


# Accept: application/json


###
